//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TezYonetimSistemi.Test.OgretmenService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ogretmen", Namespace="http://schemas.datacontract.org/2004/07/TezYonetimSistemi.Model")]
    [System.SerializableAttribute()]
    public partial class Ogretmen : TezYonetimSistemi.Test.OgretmenService.BaseModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnvanField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Unvan {
            get {
                return this.UnvanField;
            }
            set {
                if ((object.ReferenceEquals(this.UnvanField, value) != true)) {
                    this.UnvanField = value;
                    this.RaisePropertyChanged("Unvan");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseModel", Namespace="http://schemas.datacontract.org/2004/07/TezYonetimSistemi.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TezYonetimSistemi.Test.OgretmenService.Ogretmen))]
    public partial class BaseModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime OlusturmaTarihiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OlusturmaTarihi {
            get {
                return this.OlusturmaTarihiField;
            }
            set {
                if ((this.OlusturmaTarihiField.Equals(value) != true)) {
                    this.OlusturmaTarihiField = value;
                    this.RaisePropertyChanged("OlusturmaTarihi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OgretmenService.IOgretmenService")]
    public interface IOgretmenService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOgretmenService/OgretmenleriGetir", ReplyAction="http://tempuri.org/IOgretmenService/OgretmenleriGetirResponse")]
        TezYonetimSistemi.Test.OgretmenService.Ogretmen[] OgretmenleriGetir();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOgretmenService/OgretmenleriGetir", ReplyAction="http://tempuri.org/IOgretmenService/OgretmenleriGetirResponse")]
        System.Threading.Tasks.Task<TezYonetimSistemi.Test.OgretmenService.Ogretmen[]> OgretmenleriGetirAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOgretmenService/OgretmenEkle", ReplyAction="http://tempuri.org/IOgretmenService/OgretmenEkleResponse")]
        TezYonetimSistemi.Test.OgretmenService.Ogretmen OgretmenEkle(TezYonetimSistemi.Test.OgretmenService.Ogretmen ogretmen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOgretmenService/OgretmenEkle", ReplyAction="http://tempuri.org/IOgretmenService/OgretmenEkleResponse")]
        System.Threading.Tasks.Task<TezYonetimSistemi.Test.OgretmenService.Ogretmen> OgretmenEkleAsync(TezYonetimSistemi.Test.OgretmenService.Ogretmen ogretmen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOgretmenService/OgretmenGuncelle", ReplyAction="http://tempuri.org/IOgretmenService/OgretmenGuncelleResponse")]
        TezYonetimSistemi.Test.OgretmenService.Ogretmen OgretmenGuncelle(TezYonetimSistemi.Test.OgretmenService.Ogretmen ogretmen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOgretmenService/OgretmenGuncelle", ReplyAction="http://tempuri.org/IOgretmenService/OgretmenGuncelleResponse")]
        System.Threading.Tasks.Task<TezYonetimSistemi.Test.OgretmenService.Ogretmen> OgretmenGuncelleAsync(TezYonetimSistemi.Test.OgretmenService.Ogretmen ogretmen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOgretmenService/OgretmenSil", ReplyAction="http://tempuri.org/IOgretmenService/OgretmenSilResponse")]
        int OgretmenSil(TezYonetimSistemi.Test.OgretmenService.Ogretmen ogretmen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOgretmenService/OgretmenSil", ReplyAction="http://tempuri.org/IOgretmenService/OgretmenSilResponse")]
        System.Threading.Tasks.Task<int> OgretmenSilAsync(TezYonetimSistemi.Test.OgretmenService.Ogretmen ogretmen);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOgretmenServiceChannel : TezYonetimSistemi.Test.OgretmenService.IOgretmenService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OgretmenServiceClient : System.ServiceModel.ClientBase<TezYonetimSistemi.Test.OgretmenService.IOgretmenService>, TezYonetimSistemi.Test.OgretmenService.IOgretmenService {
        
        public OgretmenServiceClient() {
        }
        
        public OgretmenServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OgretmenServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OgretmenServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OgretmenServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TezYonetimSistemi.Test.OgretmenService.Ogretmen[] OgretmenleriGetir() {
            return base.Channel.OgretmenleriGetir();
        }
        
        public System.Threading.Tasks.Task<TezYonetimSistemi.Test.OgretmenService.Ogretmen[]> OgretmenleriGetirAsync() {
            return base.Channel.OgretmenleriGetirAsync();
        }
        
        public TezYonetimSistemi.Test.OgretmenService.Ogretmen OgretmenEkle(TezYonetimSistemi.Test.OgretmenService.Ogretmen ogretmen) {
            return base.Channel.OgretmenEkle(ogretmen);
        }
        
        public System.Threading.Tasks.Task<TezYonetimSistemi.Test.OgretmenService.Ogretmen> OgretmenEkleAsync(TezYonetimSistemi.Test.OgretmenService.Ogretmen ogretmen) {
            return base.Channel.OgretmenEkleAsync(ogretmen);
        }
        
        public TezYonetimSistemi.Test.OgretmenService.Ogretmen OgretmenGuncelle(TezYonetimSistemi.Test.OgretmenService.Ogretmen ogretmen) {
            return base.Channel.OgretmenGuncelle(ogretmen);
        }
        
        public System.Threading.Tasks.Task<TezYonetimSistemi.Test.OgretmenService.Ogretmen> OgretmenGuncelleAsync(TezYonetimSistemi.Test.OgretmenService.Ogretmen ogretmen) {
            return base.Channel.OgretmenGuncelleAsync(ogretmen);
        }
        
        public int OgretmenSil(TezYonetimSistemi.Test.OgretmenService.Ogretmen ogretmen) {
            return base.Channel.OgretmenSil(ogretmen);
        }
        
        public System.Threading.Tasks.Task<int> OgretmenSilAsync(TezYonetimSistemi.Test.OgretmenService.Ogretmen ogretmen) {
            return base.Channel.OgretmenSilAsync(ogretmen);
        }
    }
}
