//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TezYonetimSistemi.Test.OgrenciService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ogrenci", Namespace="http://schemas.datacontract.org/2004/07/TezYonetimSistemi.Model")]
    [System.SerializableAttribute()]
    public partial class Ogrenci : TezYonetimSistemi.Test.OgrenciService.BaseModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OgrenciNumarasiField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OgrenciNumarasi {
            get {
                return this.OgrenciNumarasiField;
            }
            set {
                if ((object.ReferenceEquals(this.OgrenciNumarasiField, value) != true)) {
                    this.OgrenciNumarasiField = value;
                    this.RaisePropertyChanged("OgrenciNumarasi");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseModel", Namespace="http://schemas.datacontract.org/2004/07/TezYonetimSistemi.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TezYonetimSistemi.Test.OgrenciService.Ogrenci))]
    public partial class BaseModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime OlusturmaTarihiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OlusturmaTarihi {
            get {
                return this.OlusturmaTarihiField;
            }
            set {
                if ((this.OlusturmaTarihiField.Equals(value) != true)) {
                    this.OlusturmaTarihiField = value;
                    this.RaisePropertyChanged("OlusturmaTarihi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OgrenciService.IOgrenciService")]
    public interface IOgrenciService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOgrenciService/OgrencileriGetir", ReplyAction="http://tempuri.org/IOgrenciService/OgrencileriGetirResponse")]
        TezYonetimSistemi.Test.OgrenciService.Ogrenci[] OgrencileriGetir();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOgrenciService/OgrencileriGetir", ReplyAction="http://tempuri.org/IOgrenciService/OgrencileriGetirResponse")]
        System.Threading.Tasks.Task<TezYonetimSistemi.Test.OgrenciService.Ogrenci[]> OgrencileriGetirAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOgrenciService/OgrenciEkle", ReplyAction="http://tempuri.org/IOgrenciService/OgrenciEkleResponse")]
        TezYonetimSistemi.Test.OgrenciService.Ogrenci OgrenciEkle(TezYonetimSistemi.Test.OgrenciService.Ogrenci ogrenci);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOgrenciService/OgrenciEkle", ReplyAction="http://tempuri.org/IOgrenciService/OgrenciEkleResponse")]
        System.Threading.Tasks.Task<TezYonetimSistemi.Test.OgrenciService.Ogrenci> OgrenciEkleAsync(TezYonetimSistemi.Test.OgrenciService.Ogrenci ogrenci);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOgrenciService/OgrenciGuncelle", ReplyAction="http://tempuri.org/IOgrenciService/OgrenciGuncelleResponse")]
        TezYonetimSistemi.Test.OgrenciService.Ogrenci OgrenciGuncelle(TezYonetimSistemi.Test.OgrenciService.Ogrenci ogrenci);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOgrenciService/OgrenciGuncelle", ReplyAction="http://tempuri.org/IOgrenciService/OgrenciGuncelleResponse")]
        System.Threading.Tasks.Task<TezYonetimSistemi.Test.OgrenciService.Ogrenci> OgrenciGuncelleAsync(TezYonetimSistemi.Test.OgrenciService.Ogrenci ogrenci);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOgrenciService/OgrenciSil", ReplyAction="http://tempuri.org/IOgrenciService/OgrenciSilResponse")]
        int OgrenciSil(TezYonetimSistemi.Test.OgrenciService.Ogrenci ogrenci);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOgrenciService/OgrenciSil", ReplyAction="http://tempuri.org/IOgrenciService/OgrenciSilResponse")]
        System.Threading.Tasks.Task<int> OgrenciSilAsync(TezYonetimSistemi.Test.OgrenciService.Ogrenci ogrenci);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOgrenciServiceChannel : TezYonetimSistemi.Test.OgrenciService.IOgrenciService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OgrenciServiceClient : System.ServiceModel.ClientBase<TezYonetimSistemi.Test.OgrenciService.IOgrenciService>, TezYonetimSistemi.Test.OgrenciService.IOgrenciService {
        
        public OgrenciServiceClient() {
        }
        
        public OgrenciServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OgrenciServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OgrenciServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OgrenciServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TezYonetimSistemi.Test.OgrenciService.Ogrenci[] OgrencileriGetir() {
            return base.Channel.OgrencileriGetir();
        }
        
        public System.Threading.Tasks.Task<TezYonetimSistemi.Test.OgrenciService.Ogrenci[]> OgrencileriGetirAsync() {
            return base.Channel.OgrencileriGetirAsync();
        }
        
        public TezYonetimSistemi.Test.OgrenciService.Ogrenci OgrenciEkle(TezYonetimSistemi.Test.OgrenciService.Ogrenci ogrenci) {
            return base.Channel.OgrenciEkle(ogrenci);
        }
        
        public System.Threading.Tasks.Task<TezYonetimSistemi.Test.OgrenciService.Ogrenci> OgrenciEkleAsync(TezYonetimSistemi.Test.OgrenciService.Ogrenci ogrenci) {
            return base.Channel.OgrenciEkleAsync(ogrenci);
        }
        
        public TezYonetimSistemi.Test.OgrenciService.Ogrenci OgrenciGuncelle(TezYonetimSistemi.Test.OgrenciService.Ogrenci ogrenci) {
            return base.Channel.OgrenciGuncelle(ogrenci);
        }
        
        public System.Threading.Tasks.Task<TezYonetimSistemi.Test.OgrenciService.Ogrenci> OgrenciGuncelleAsync(TezYonetimSistemi.Test.OgrenciService.Ogrenci ogrenci) {
            return base.Channel.OgrenciGuncelleAsync(ogrenci);
        }
        
        public int OgrenciSil(TezYonetimSistemi.Test.OgrenciService.Ogrenci ogrenci) {
            return base.Channel.OgrenciSil(ogrenci);
        }
        
        public System.Threading.Tasks.Task<int> OgrenciSilAsync(TezYonetimSistemi.Test.OgrenciService.Ogrenci ogrenci) {
            return base.Channel.OgrenciSilAsync(ogrenci);
        }
    }
}
