//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TezYonetimSistemi.Test.KullaniciService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Kullanici", Namespace="http://schemas.datacontract.org/2004/07/TezYonetimSistemi.Model")]
    [System.SerializableAttribute()]
    public partial class Kullanici : TezYonetimSistemi.Test.KullaniciService.BaseModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FotografField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RolIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SifreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoyadField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ad {
            get {
                return this.AdField;
            }
            set {
                if ((object.ReferenceEquals(this.AdField, value) != true)) {
                    this.AdField = value;
                    this.RaisePropertyChanged("Ad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fotograf {
            get {
                return this.FotografField;
            }
            set {
                if ((object.ReferenceEquals(this.FotografField, value) != true)) {
                    this.FotografField = value;
                    this.RaisePropertyChanged("Fotograf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mail {
            get {
                return this.MailField;
            }
            set {
                if ((object.ReferenceEquals(this.MailField, value) != true)) {
                    this.MailField = value;
                    this.RaisePropertyChanged("Mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RolID {
            get {
                return this.RolIDField;
            }
            set {
                if ((this.RolIDField.Equals(value) != true)) {
                    this.RolIDField = value;
                    this.RaisePropertyChanged("RolID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sifre {
            get {
                return this.SifreField;
            }
            set {
                if ((object.ReferenceEquals(this.SifreField, value) != true)) {
                    this.SifreField = value;
                    this.RaisePropertyChanged("Sifre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Soyad {
            get {
                return this.SoyadField;
            }
            set {
                if ((object.ReferenceEquals(this.SoyadField, value) != true)) {
                    this.SoyadField = value;
                    this.RaisePropertyChanged("Soyad");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseModel", Namespace="http://schemas.datacontract.org/2004/07/TezYonetimSistemi.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TezYonetimSistemi.Test.KullaniciService.Kullanici))]
    public partial class BaseModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime OlusturmaTarihiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OlusturmaTarihi {
            get {
                return this.OlusturmaTarihiField;
            }
            set {
                if ((this.OlusturmaTarihiField.Equals(value) != true)) {
                    this.OlusturmaTarihiField = value;
                    this.RaisePropertyChanged("OlusturmaTarihi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KullaniciService.IKullaniciService")]
    public interface IKullaniciService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKullaniciService/KullanicilariGetir", ReplyAction="http://tempuri.org/IKullaniciService/KullanicilariGetirResponse")]
        TezYonetimSistemi.Test.KullaniciService.Kullanici[] KullanicilariGetir();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKullaniciService/KullanicilariGetir", ReplyAction="http://tempuri.org/IKullaniciService/KullanicilariGetirResponse")]
        System.Threading.Tasks.Task<TezYonetimSistemi.Test.KullaniciService.Kullanici[]> KullanicilariGetirAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKullaniciService/KullaniciEkle", ReplyAction="http://tempuri.org/IKullaniciService/KullaniciEkleResponse")]
        TezYonetimSistemi.Test.KullaniciService.Kullanici KullaniciEkle(TezYonetimSistemi.Test.KullaniciService.Kullanici kullanici);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKullaniciService/KullaniciEkle", ReplyAction="http://tempuri.org/IKullaniciService/KullaniciEkleResponse")]
        System.Threading.Tasks.Task<TezYonetimSistemi.Test.KullaniciService.Kullanici> KullaniciEkleAsync(TezYonetimSistemi.Test.KullaniciService.Kullanici kullanici);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKullaniciService/KullaniciGuncelle", ReplyAction="http://tempuri.org/IKullaniciService/KullaniciGuncelleResponse")]
        TezYonetimSistemi.Test.KullaniciService.Kullanici KullaniciGuncelle(TezYonetimSistemi.Test.KullaniciService.Kullanici kullanici);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKullaniciService/KullaniciGuncelle", ReplyAction="http://tempuri.org/IKullaniciService/KullaniciGuncelleResponse")]
        System.Threading.Tasks.Task<TezYonetimSistemi.Test.KullaniciService.Kullanici> KullaniciGuncelleAsync(TezYonetimSistemi.Test.KullaniciService.Kullanici kullanici);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKullaniciService/KullaniciSil", ReplyAction="http://tempuri.org/IKullaniciService/KullaniciSilResponse")]
        int KullaniciSil(TezYonetimSistemi.Test.KullaniciService.Kullanici kullanici);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKullaniciService/KullaniciSil", ReplyAction="http://tempuri.org/IKullaniciService/KullaniciSilResponse")]
        System.Threading.Tasks.Task<int> KullaniciSilAsync(TezYonetimSistemi.Test.KullaniciService.Kullanici kullanici);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKullaniciServiceChannel : TezYonetimSistemi.Test.KullaniciService.IKullaniciService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KullaniciServiceClient : System.ServiceModel.ClientBase<TezYonetimSistemi.Test.KullaniciService.IKullaniciService>, TezYonetimSistemi.Test.KullaniciService.IKullaniciService {
        
        public KullaniciServiceClient() {
        }
        
        public KullaniciServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KullaniciServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KullaniciServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KullaniciServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TezYonetimSistemi.Test.KullaniciService.Kullanici[] KullanicilariGetir() {
            return base.Channel.KullanicilariGetir();
        }
        
        public System.Threading.Tasks.Task<TezYonetimSistemi.Test.KullaniciService.Kullanici[]> KullanicilariGetirAsync() {
            return base.Channel.KullanicilariGetirAsync();
        }
        
        public TezYonetimSistemi.Test.KullaniciService.Kullanici KullaniciEkle(TezYonetimSistemi.Test.KullaniciService.Kullanici kullanici) {
            return base.Channel.KullaniciEkle(kullanici);
        }
        
        public System.Threading.Tasks.Task<TezYonetimSistemi.Test.KullaniciService.Kullanici> KullaniciEkleAsync(TezYonetimSistemi.Test.KullaniciService.Kullanici kullanici) {
            return base.Channel.KullaniciEkleAsync(kullanici);
        }
        
        public TezYonetimSistemi.Test.KullaniciService.Kullanici KullaniciGuncelle(TezYonetimSistemi.Test.KullaniciService.Kullanici kullanici) {
            return base.Channel.KullaniciGuncelle(kullanici);
        }
        
        public System.Threading.Tasks.Task<TezYonetimSistemi.Test.KullaniciService.Kullanici> KullaniciGuncelleAsync(TezYonetimSistemi.Test.KullaniciService.Kullanici kullanici) {
            return base.Channel.KullaniciGuncelleAsync(kullanici);
        }
        
        public int KullaniciSil(TezYonetimSistemi.Test.KullaniciService.Kullanici kullanici) {
            return base.Channel.KullaniciSil(kullanici);
        }
        
        public System.Threading.Tasks.Task<int> KullaniciSilAsync(TezYonetimSistemi.Test.KullaniciService.Kullanici kullanici) {
            return base.Channel.KullaniciSilAsync(kullanici);
        }
    }
}
